// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsZaQLGK8I1WMImoohIZy4B-PTStqoS7k',
    appId: '1:956439373630:web:8bc6b449ef9249e1346e6f',
    messagingSenderId: '956439373630',
    projectId: 'bite-and-burp-pos',
    authDomain: 'bite-and-burp-pos.firebaseapp.com',
    storageBucket: 'bite-and-burp-pos.firebasestorage.app',
    measurementId: 'G-D72Z7KEXNC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrFtkovxi8JPMTmmIhXw8UdZqGA7kjSeU',
    appId: '1:956439373630:android:433dab42cc97331e346e6f',
    messagingSenderId: '956439373630',
    projectId: 'bite-and-burp-pos',
    storageBucket: 'bite-and-burp-pos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5T-UE48ENamgY2OuBRnTJgi5h9kQPB5k',
    appId: '1:956439373630:ios:3350c360b2688db0346e6f',
    messagingSenderId: '956439373630',
    projectId: 'bite-and-burp-pos',
    storageBucket: 'bite-and-burp-pos.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5T-UE48ENamgY2OuBRnTJgi5h9kQPB5k',
    appId: '1:956439373630:ios:3350c360b2688db0346e6f',
    messagingSenderId: '956439373630',
    projectId: 'bite-and-burp-pos',
    storageBucket: 'bite-and-burp-pos.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsZaQLGK8I1WMImoohIZy4B-PTStqoS7k',
    appId: '1:956439373630:web:69e4bd81a4299aa6346e6f',
    messagingSenderId: '956439373630',
    projectId: 'bite-and-burp-pos',
    authDomain: 'bite-and-burp-pos.firebaseapp.com',
    storageBucket: 'bite-and-burp-pos.firebasestorage.app',
    measurementId: 'G-XC2N87FD5T',
  );
}
